### ISSUE TITLE
Data seeding management

### ISSUE THREAD

**Issue by jmaicaaan** [jmaicaaan/express-starter-ts#25]
- [ ] Remove the initial seed under migration. A migration should not have a seeding!

**Comment by jmaicaaan** [comment]
- [ ] Remove the initial seed under migration. A migration should not have a seeding!

**Comment by jmaicaaan** [comment]
- Should we delete the seeding in the migration and make it a breaking change? Because if we create another migration in removing the seeding that would add another file which is kind of useless 🤔

**Comment by ciiidi** [comment]
Hmm I think we should only isolate the seeds that does not depend on migration, what's on my mind is that seeding has two parts the version control seed and independent seed. the VCS (version control seed) will still be on migration folder while the Indepnt Seed will be isolated because it will run multiple times more than the migration, I think the meaning of independent seeding is just for the database to have a tests data, but the VCS will still be part of migration and the INSERT Roles command we have is still part of it.

**Comment by ciiidi** [comment]
Imagine, we will run the migration, it will create the structure of our database. That's all
Then we will seed it using our seeding scripts.
Then somewhere on the future we create another migration we update the database.
Then we cannot assure if our seed files will still work. That's why it breaks into two the VCS and IS
The VCS will still be part of the migrations and only the IS will be isolated. Actually I don't have any structure and conditions on how we will know if its a VCS or IS. Give me some time maybe we can talk about it. because it will add another structure and I am anticipating that it will break the structures that we have right now. it will be a big change.
